[features]
seeds = false
skip-lint = false
[programs.localnet]
calculator = "dp9fQT31NF7f84h6PoSDdwSF4cK6UFGYiJpFdzxtDdE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/eog/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
